name: "terraform-destroy"

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Test'
        required: true
        default: 'Test'
        type: choice
        options:
        - Test

jobs:
  Terraform_AWS_Resume:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_REGION_ACM: ${{ secrets.AWS_REGION_ACM }}
  
      CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
      ZONE_ID: ${{ secrets.ZONE_ID }}
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}

      #jwtSecret: ${{ secrets.JWT_SECRET }} #github secret

    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform test
        uses: actions/checkout@v3

      - name: Terraform Destroy all
        run: terraform destroy -auto-approve
        env:
          TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          TF_VAR_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          TF_VAR_region: ${{ secrets.AWS_REGION }}
          TF_VAR_region_acm: ${{ secrets.AWS_REGION_ACM }}

          TF_VAR_cloudflare_token: ${{ secrets.CLOUDFLARE_TOKEN }}
          TF_VAR_zone_id: ${{ secrets.ZONE_ID }}
          TF_VAR_account_id: ${{ secrets.ACCOUNT_ID }}

          TF_VAR_domain: "*.keysersozeresume.uk"
          TF_VAR_domain_firstname: "stefandi"
          TF_VAR_s3_folder_location_upload: "resume"

          TF_VAR_tags: "keysersoze"
          TF_VAR_lambda_function_name: "totalViewer"
          TF_VAR_api_gateway_stage_name: "views"



          #TF_VAR_jwtSecret: ${{ secrets.JWT_SECRET }}